import React from "react";
import Head from "next/head";
import CustomAppShell from "@/components/CustomAppShell";

function Chat() {
    return (
        <>
            <Head>
                <title>CAP23</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CustomAppShell selectedTab="chat">
                    
                </CustomAppShell>
            </main>
        </>
    );
}

export default Chat;