import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { AppShell, Navbar, Text, ActionIcon, Group, Tooltip, } from '@mantine/core'
import CustomNavbar from '@/components/Navbar'
import { IconChevronLeft } from "@tabler/icons"

export default function Courses() {

  return (
    <>
      <Head>
        <title>CAP23</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppShell

          navbar={<Navbar width={{ base: 200 }} height={"100%"} p="xs">

            <CustomNavbar selectedTab='courses' />

          </Navbar>}

        >
          <Group position="apart" style={{ width: "100vw" }}>
            <ActionIcon variant="outline" size="lg">
              <IconChevronLeft size={22} />
            </ActionIcon>
          </Group>

        </AppShell>
      </main>
    </>
  )
}
