import Head from "next/head";
import CoursesContent from "@/components/course-components/CoursesContent";
import CustomAppShell from "@/components/CustomAppShell";
import { useState, Children } from "react";
import AddCourseModal from "@/components/course-components/AddCourseModal";
import { IconBooks } from "@tabler/icons";
import EditCourseModal from "@/components/course-components/EditCourseModal";
import CourseCard from "@/components/course-components/CourseCard";
import { createStyles } from "@mantine/core";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (context) => {
	const courses = [
		{
			courseName: "Introduction to Computer Science",
			courseTeacher: "John Smith",
			previewIconIndex: 1,
			backgroundColorIndex: 0,
		},
		{
			courseName: "Linear Algebra",
			courseTeacher: "Emily Johnson",
			previewIconIndex: 7,
			backgroundColorIndex: 1,
		},
		{
			courseName: "Shakespearean Literature",
			courseTeacher: "William Brown",
			previewIconIndex: 0,
			backgroundColorIndex: 2,
		},
		{
			courseName: "Philosophy of Ethics",
			courseTeacher: "Sarah Lee",
			previewIconIndex: 3,
			backgroundColorIndex: 3,
		},
	];

	// const courses: any[] = [];

	return {
		props: {
			courses: courses,
		},
	};
};

type CoursesProps = {
	courses: {
		courseName: string;
		courseTeacher: string;
		previewIconIndex: number;
		backgroundColorIndex: number;
	}[];
};

export default function Courses({ courses }: CoursesProps) {
	const [addCourseModalIsOpen, setAddCourseModalIsOpen] = useState(false);
	const [editCourseModalIsOpen, setEditCourseModalIsOpen] = useState(false);
	const [currentCourseProperties, setCurrentCourseProperties] = useState({
		title: "",
		teacher: "",
		icon: <IconBooks size={30} />,
	});
	const [courseArray, setCourseArray] = useState(courses);

	return (
		<>
			<Head>
				<title>CAP23</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<AddCourseModal
					courseArray={courseArray}
					setCourseArray={setCourseArray}
					addCourseModalIsOpen={addCourseModalIsOpen}
					setAddCourseModalIsOpen={setAddCourseModalIsOpen}
				/>
				<EditCourseModal
					courseArray={courseArray}
					setCourseArray={setCourseArray}
					editCourseModalIsOpen={editCourseModalIsOpen}
					setEditCourseModalIsOpen={setEditCourseModalIsOpen}
					currentCourseProperties={currentCourseProperties}
					setCurrentCourseProperties={setCurrentCourseProperties}
				/>
				<CustomAppShell selectedTab="courses">
					<CoursesContent
						setAddCourseModalIsOpen={setAddCourseModalIsOpen}
						setEditCourseModalIsOpen={setEditCourseModalIsOpen}
						setCurrentCourseProperties={setCurrentCourseProperties}
						courseArray={courseArray}
						setCourseArray={setCourseArray}
					/>
				</CustomAppShell>
			</main>
		</>
	);
}
