import Head from "next/head";
import CustomAppShell from "@/components/CustomAppShell";
import SupportContent from "@/components/support-components/SupportContent";

import { GetServerSideProps } from "next";
import { useState } from "react";

// export const getServerSideProps: GetServerSideProps = async (context) => {
// 	const messages = [
// 		{
// 			isAssistant: true,
// 			content:
// 				"Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minima repudiandae accusamus sequi est cumque voluptate, quia laboriosam nostrum veniam illo accusantium iusto officiis nam dignissimos culpa hic obcaecati. Maiores.",
// 			timestamp: new Date().toJSON(),
// 		},
// 		{
// 			isAssistant: false,
// 			content: "nam dignissimos culpa hic obcaecati. Maiores.",
// 			timestamp: new Date().toJSON(),
// 		},
// 	];

// 	return {
// 		props: {
// 			messages: messages,
// 		},
// 	};
// };

// type SupportProps = {
// 	messages: { isAssistant: boolean; content: string; timestamp: string }[];
// };

function Support() {
	const [messageData, setMessageData] = useState([
		{
			isAssistant: true,
			content:
				"Hello",
			timestamp: new Date(),
		},
		{
			isAssistant: false,
			content: "nam dignissimos culpa hic obcaecati. Maiores.",
			timestamp: new Date(),
		},
	]);

	return (
		<>
			<Head>
				<title>CAP23</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<CustomAppShell selectedTab="support">
					<SupportContent messages={messageData} />
				</CustomAppShell>
			</main>
		</>
	);
}

export default Support;
